### ISSUE TITLE
Defaultuser

### ISSUE THREAD

**Issue by tebbbb** [unopim/unopim#20]
### Is your feature request related to a problem? Please describe.

It would be nice to have an admin default user or a console command to create one.

### Describe the solution you'd like

As seen above

**Comment by devansh-pal-webkul** [comment]
@tebbbb ,
Currently, we do not have a command to create a user directly but we will add this feature in one of our next upcoming releases. 

You can create a new user using the installation command `php artisan unopim:install`.

If you have run the `php artisan db:seed` command, the default user credentials will be as follows:

- Email: admin@example.com
- Password: admin123

**Comment by navneetbhardwaj** [comment]
The `user:create` command has been introduced in version **v0.1.5**. You can utilize it as follows:

```bash
php artisan unopim:user:create --name="username" --email="useremail" --password="userpassword" --ui_locale="locale_code" --timezone="timezone" --admin
```

This command allows you to specify user details such as name, email, password, UI locale, timezone, and admin privileges.

Closing this issue as resolved.
