### ISSUE TITLE
Seeder not working correctly

### ISSUE THREAD

**Issue by tebbbb** [unopim/unopim#21]
### Terms

- [X] Before you open this issue, I have checked if the issue has already been reported.

### UnoPim Version(s) affected

latest as of today

### Issue Description

root@b05328390c77:/var/www/html# php artisan db:seed        

   INFO  Seeding database.  

  Webkul\Installer\Database\Seeders\DatabaseSeeder ......................................................................................... RUNNING  
  Webkul\Installer\Database\Seeders\Attribute\DatabaseSeeder ............................................................................... RUNNING  
  Webkul\Installer\Database\Seeders\Attribute\AttributeGroupTableSeeder .................................................................... RUNNING  
  Webkul\Installer\Database\Seeders\Attribute\AttributeGroupTableSeeder ................................................................. 21 ms DONE  

  Webkul\Installer\Database\Seeders\Attribute\AttributeTableSeeder ......................................................................... RUNNING  
  Webkul\Installer\Database\Seeders\Attribute\AttributeTableSeeder ...................................................................... 11 ms DONE  

  Webkul\Installer\Database\Seeders\Attribute\AttributeOptionTableSeeder ................................................................... RUNNING  
  Webkul\Installer\Database\Seeders\Attribute\AttributeOptionTableSeeder ................................................................. 5 ms DONE  

  Webkul\Installer\Database\Seeders\Attribute\AttributeFamilyTableSeeder ................................................................... RUNNING  
  Webkul\Installer\Database\Seeders\Attribute\AttributeFamilyTableSeeder ................................................................. 9 ms DONE  

  Webkul\Installer\Database\Seeders\Attribute\DatabaseSeeder ............................................................................ 51 ms DONE  

  Webkul\Installer\Database\Seeders\Category\DatabaseSeeder ................................................................................ RUNNING  
  Webkul\Installer\Database\Seeders\Category\CategoryTableSeeder ........................................................................... RUNNING  
  Webkul\Installer\Database\Seeders\Category\CategoryTableSeeder ......................................................................... 4 ms DONE  

  Webkul\Installer\Database\Seeders\Category\CategoryFieldTableSeeder ...................................................................... RUNNING  
  Webkul\Installer\Database\Seeders\Category\CategoryFieldTableSeeder .................................................................... 6 ms DONE  

  Webkul\Installer\Database\Seeders\Category\DatabaseSeeder ............................................................................. 12 ms DONE  

  Webkul\Installer\Database\Seeders\Core\DatabaseSeeder .................................................................................... RUNNING  
  Webkul\Installer\Database\Seeders\Core\LocalesTableSeeder ................................................................................ RUNNING  

In Connection.php line 829:
                                                                                                                                                                
  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`unopim`.`admins`, CONSTRAINT `a  
  dmins_ui_locale_id_foreign` FOREIGN KEY (`ui_locale_id`) REFERENCES `locales` (`id`)) (Connection: mysql, SQL: delete from `locales`)                         
                                                                                                                                                                

In Connection.php line 612:
                                                                                                                                                                
  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`unopim`.`admins`, CONSTRAINT `a  
  dmins_ui_locale_id_foreign` FOREIGN KEY (`ui_locale_id`) REFERENCES `locales` (`id`))        

### Preconditions

Fresh installation

### Steps to reproduce

Go into the docker container, run php artisan db:seed

### Expected Result

/

### Actual Result

See above

**Comment by devansh-pal-webkul** [comment]
@tebbbb , 

Thank you for reporting the issue. We have fixed it in the master branch, but it hasn't been released yet. We will aim to release this as a patch soon.

In the meantime, you can avoid the issue by running the following command:
`php artisan migrate:fresh --seed`

Otherwise you can use the installation command `php artisan unopim:install`.

**Comment by devansh-pal-webkul** [comment]
Fix added in v0.1.3
