### ISSUE TITLE
Managing a one to many relationship

### ISSUE THREAD

**Issue by helgvor-stoll** [unopim/unopim#23]
### Is your feature request related to a problem? Please describe.

In the attributes, it's possible to manage different types of field (text, select, images...). It's a one to one field but for images, it should be nice to have multiple images for one product.

### Describe the solution you'd like

Is it possible to add a select dropdown box to select the relationship of the field under the type:
![image](https://github.com/user-attachments/assets/a67a7fa2-d20a-421f-83a8-102f210483d8)
In this case, the field wil be saved as an array in the values fields

**Comment by helgvor-stoll** [comment]
@navneetbhardwaj
Super. Thank you

**Comment by devansh-pal-webkul** [comment]
Added in [v0.1.3](https://github.com/unopim/unopim/releases/tag/v0.1.3)
