### ISSUE TITLE
Datagrid improvement

### ISSUE THREAD

**Issue by helgvor-stoll** [unopim/unopim#25]
### Is your feature request related to a problem? Please describe.

On the datagrid, we have only the next an previous functionality:
![image](https://github.com/user-attachments/assets/9ecb3092-cb75-4f06-a1e1-9ca345e072cc)

### Describe the solution you'd like

When there many records and a lot of pages, it should be useful have the possibility to go directly at the last and/or the first page.
Could it be possible to new 2 new buttons to access the last and the first pagination pages?

**Comment by navneetbhardwaj** [comment]
@helgvor-stoll 

Thank you for your suggestion! We understand how useful first and last page buttons can be for navigating through large datasets. However, I'd like to point out that our current datagrid allows users to directly enter the page number in the input box and press enter, enabling you to jump to any specific page, including the first and last. This provides flexibility without additional buttons.

![image](https://github.com/user-attachments/assets/481014fe-1844-4f10-b2c2-52078d928963)
