### ISSUE TITLE
Profile update

### ISSUE THREAD

**Issue by helgvor-stoll** [unopim/unopim#26]
### Is your feature request related to a problem? Please describe.

The Timezone & Locale from the user is available in the Setings > User from but not in the profile form
![image](https://github.com/user-attachments/assets/bb69f58a-0786-4c3e-9f8f-362e4983efa4)

### Describe the solution you'd like

Should it be possible to add these 2 fields in the profile form. In this case, even if a user don't have the access to the Settings > Users, he can change his own language and timezone data from the profile
![image](https://github.com/user-attachments/assets/53678589-dbf3-48b9-8362-f156d609c029)

**Comment by navneetbhardwaj** [comment]
@helgvor-stoll 

Thank you for bringing this up! It makes sense that users should be able to update their own language and timezone settings, even if they don't have access to the broader Settings > Users section.

We'll look into the possibility of adding these two fields—Locale and Timezone—to the user profile form. This would allow users to manage their own preferences directly from their profile, improving accessibility and personalization.

**Comment by helgvor-stoll** [comment]
@navneetbhardwaj Very fine, thank you

**Comment by devansh-pal-webkul** [comment]
Added in [v0.1.3](https://github.com/unopim/unopim/releases/tag/v0.1.3)
