### ISSUE TITLE
The datagrid of categories doesn't work

### ISSUE THREAD

**Issue by helgvor-stoll** [unopim/unopim#3]
### Terms

- [X] Before you open this issue, I have checked if the issue has already been reported.

### UnoPim Version(s) affected

0.1.1

### Issue Description

When you go on "categories" menu, nothing is showed in the datagrid. It looks like it is empty, even if you create one

### Preconditions

nothing special

### Steps to reproduce

1. Go to 'categories' menu

### Expected Result

A datagrid with the category records if it exists

### Actual Result

Empty datagrid

### Screenshots

![2024-09-02_10-00-12](https://github.com/user-attachments/assets/7e1bfa3f-bf60-4c34-914d-d1bb78b439f1)

**Comment by helgvor-stoll** [comment]
Perhaps it's because no translation field is available when filling the name and description fields.
![image](https://github.com/user-attachments/assets/7edb4273-7b25-42f8-9d5d-7dac67ccda0a)

**Comment by helgvor-stoll** [comment]
I found the problem. I think that the demo version use PostgreSQL, that's why it works on the demo version. But in the in the packages\Webkul\Admin\src\Datagrids\Settings\ChannelDataGrid.php file, the method prepareQueryBuilder() is written to work with PostgreSQL and not MariaDB.
In fact, sql in MariaDB don't recognize the Json SQL Syntax additional_data->'$.locale_specific.en_US.name' (for example) but use instead the syntax: json_extract(additional_data, '$.locale_specific.en_US.name').
The correction have to be done in the bold part of the method:

    public function prepareQueryBuilder()
    {
        $requestedLocaleCode = core()->getRequestedLocaleCode();

        $fallbackLocaleCode = app()->getFallbackLocale();

        $tablePrefix = DB::getTablePrefix();

        $queryBuilder = DB::table('channels')
            ->leftJoin('channel_translations as requested_channel_translation', function ($leftJoin) use ($requestedLocaleCode) {
                $leftJoin->on('requested_channel_translation.channel_id', '=', 'channels.id')
                    ->where('requested_channel_translation.locale', $requestedLocaleCode);

            })
            ->leftJoin('channel_translations as fallback_channel_translation', function ($leftJoin) use ($fallbackLocaleCode) {
                $leftJoin->on('fallback_channel_translation.channel_id', '=', 'channels.id')
                    ->where('fallback_channel_translation.locale', $fallbackLocaleCode);

            })
            ->leftJoin('categories', function ($leftJoin) {
                $leftJoin->on('categories.id', '=', 'channels.root_category_id');
            })
            ->select(
                'channels.id',
                'channels.code',
                'channels.root_category_id',
                **DB::raw('(CASE WHEN CHAR_LENGTH(TRIM('.$tablePrefix.'requested_channel_translation.name)) < 1 THEN '.$tablePrefix.'fallback_channel_translation.name ELSE '.$tablePrefix.'requested_channel_translation.name END) as translated_name'),**
                **DB::raw('(CASE WHEN '.$tablePrefix."categories.additional_data->'$.locale_specific.".$requestedLocaleCode.".name' IS NOT NULL THEN REPLACE(additional_data->'$.locale_specific.".$requestedLocaleCode.".name', '\"', '') ELSE CONCAT('[', ".$tablePrefix."categories.code, ']') END) as translated_category_name")**
            );

        $this->addFilter('id', 'channels.id');
        $this->addFilter('code', 'channels.code');
        $this->addFilter('translated_name', 'requested_channel_translation.name');
        **$this->addFilter('translated_category_name', DB::raw('(CASE WHEN '.$tablePrefix."categories.additional_data->'$.locale_specific.".$requestedLocaleCode.".name' IS NOT NULL THEN REPLACE(additional_data->'$.locale_specific.".$requestedLocaleCode.".name', '\"', '') ELSE ".$tablePrefix.'categories.code END)'));**

        return $queryBuilder;
    }

Thank you in advance for fixing
Kind Regards

**Comment by navneetbhardwaj** [comment]
@helgvor-stoll, at this time, our project only supports MySQL databases. The issue you're encountering is likely due to the use of a MariaDB database. We will look into adding MariaDB support in future releases.

**Comment by navneetbhardwaj** [comment]
@helgvor-stoll  
Thank you for the update! We appreciate your contribution to making Unopim compatible with MariaDB. We'll review the changes in the \Webkul\Admin\src\Datagrids\Settings\ChannelDataGrid.php and \Webkul\Admin\src\Datagrids\Catalog\CategoryDataGrid.php files to ensure compatibility and alignment with our project standards. Your efforts help improve the flexibility and accessibility of Unopim. We'll check the feasibility and update as necessary. Thanks again for your valuable input!

**Comment by navneetbhardwaj** [comment]
Added in [v0.1.2](https://github.com/unopim/unopim/releases/tag/v0.1.2)
