### ISSUE TITLE
Add Variants Support with attribute and terms

### ISSUE THREAD

**Issue by Giacomo92** [unopim/unopim#33]
### Is your feature request related to a problem? Please describe.

 Product system with variants allows a base product to have multiple versions, differing by attributes like size, color, or material. Each unique combination forms a variant with its own SKU, inventory, and sometimes pricing, all managed under a single product listing.

### Describe the solution you'd like

Here a possibile solution (to be expand):
- Add the ability to handle attributes: Create a system where each product can have customizable attributes (like size, color, etc.) linked to it.
- Add the ability to handle terms: Implement a taxonomy to manage different terms (values) for each attribute, such as "red," "blue" for color or "small," "large" for size.

**Comment by devansh-pal-webkul** [comment]
Hi @Giacomo92 ,

Here is how we are managing the variants and their values:

Add the ability to handle attributes:
- For variant products, we manage configurable attributes such as color and size through attribute families. All select type attributes that are not channel or locale-specific within an attribute family can be used to create configurable products with variants. As shown in the image below, when creating a configurable product, you can select configurable attributes that are customizable for that product's variants. Only select type attributes are displayed here.
- ![configurable-attributes-with-product](https://github.com/user-attachments/assets/32e4f232-fef4-46d6-bc02-028d129ef135)


Add the ability to handle terms:
- To manage different values for an attribute, such as a variant's configurable attribute (e.g., "color"), we utilize attribute options for select type attributes. To create a new attribute option, navigate to the attribute edit page and scroll down to the options section, where you can manage the various values for that attribute.
- ![variant-options](https://github.com/user-attachments/assets/7f6d2b46-7855-49ae-b620-571c39595e87)


If you meant something else and we have misinterpreted please let us know.

**Comment by navneetbhardwaj** [comment]
Thank you for your question. This issue is now being closed, but please feel free to reopen it if further clarification or assistance is needed.
Best regards.
