### ISSUE TITLE
Separation between locale and channel

### ISSUE THREAD

**Issue by helgvor-stoll** [unopim/unopim#4]
### Is your feature request related to a problem? Please describe.

It's really disturbing to manage a product present in different channels and locales at the same time by using the dropdown buttons on the top of the product form as it's very difficult to have an overview of what is done and what have to be done:
![image](https://github.com/user-attachments/assets/32608547-0082-4201-aede-9304f38dc399)
As the product form is a result of a combination of locale x channel, we have to test all the combination to be sure that every fiels are filled....

### Describe the solution you'd like

I propose to decouple/separate the locale dependancy from the channel dependancy. A good way (according to me) is to keep the locale dependancy and a default channel value (which can be empty) on the product form and a new form to manage only the channel dependancy data. By this way, we can have a fallback channel value in case if it's informed on the product form.

### Describe alternatives you've considered

Please consider the case of a catalog of products we want to sell in different countries (one country = one channel) but the purchase (in the case of we have different warehouses for the channels for example) and sale prices are different for the countries. We want to sell for example in France (locale = fr), Belgium (locale in [nl, fr]), Luxemburg(locale in [fr, nl, de]) but the name and the description is mainly locale dependant (but why not, can be channel dependant) and the purchase price and the sale price are channel dependant (and as before, why not for the name or description).
On the product form we can have the name, description, puchase price and sale price and only the locale dropdown button. By this way, we can manage the translation of the name and the description on this form and put a default value for both, purchase price and sale price.
On the channel_product form, we will then have the fields purchase price and sale price (and name and description if it is channel dependant too) but no dropdown button as the fields are only channel dependants.
By using the mandatory value (is required) on the attribute parameter, we can then force the input of a channel data or let it empty and use the product data instead. It's a kind of overloading/inheritance and i think it will be more flexible in practice.

**Comment by navneetbhardwaj** [comment]
@helgvor-stoll,

Thank you for your detailed feature request and the insights you've provided.

We understand the challenges of managing products across different channels and locales, especially ensuring all fields are accurately filled for each combination. Your suggestion to decouple locale and channel dependencies is thoughtful and could potentially simplify product management.

We already have a roadmap in place for feature completeness, which will be included in the upcoming major release. You'll be able to see this soon.

According to PIM standards, it's not possible to separate locale dependencies from channels. However, for fallback purposes, you can create a default channel with the available locales of your business and use it as the fallback channel.

**Currencies:**
For managing different prices across channels, you can add multiple currencies to a channel. Currency selection is not dependent on locales—only localization and scopable fields depend on channels and locales.

**Next Steps:**
1. We'll review the technical feasibility of your suggestion in the context of our current roadmap and PIM standards.
2. We encourage you to explore creating a default channel for fallback purposes as a potential interim solution.

**Comment by helgvor-stoll** [comment]
@navneetbhardwaj 
Hi. I just had a look at the database and have some suggestions for the product management and the channels.
I think that the "values" field of the products table doesn't have to contain the channel key. Another table (product_channels for example) could contain the channel data (channel_id, product_id, values).
In this way, the products table contains the fallback values and we can or not adapt the different data for a given channel.
We use intensively this approach in Sage X3 ERP system which consist of a mix of inheritance and overriding of data. In our case, that means that we have a kind of data initialization chain in 3 layers:

- Folder layer/level
- Product layer
- Channel layer

When recovering a data, we then go through this layers in the same order as described. If the data exists in the folder layer (in .env file for example), we then initialize the data with its value. We repeat this until the channel layer.
We can work in a downtop way to for performance reasons and begin from the channel until a value is found.

In this way, we can imagine that the product user interface consist in 2 forms:

- One to manage the products with a multi-locale tab or dropdown select box (as it's done in unopim now). In this form, we can then add a checkbox list to select in which channels we want to put this product. For example, I developed this UI for my e-commerce business a few years ago to manage  my own PIM
![image](https://github.com/user-attachments/assets/b9f8c832-9980-440f-9d14-a71d927cce93)
- The second form will deal with the channel data of the product. In this case, the data which are not concerned by the channel variation can be readonly. The "key" of the form is then product_id+channel_id and it's aim at updating the "product_channels.values" json field (values is then a pivot attribute of the intermediate table associated to the many2many relationship between products & channels).

What do you think about this? As a user, the PIM have to be concise and easy to use. Many information must be well organised in order to have a clear vision of your catalog.
